
template: Hello, %s!
defaultName: Stranger

server:
  type: simple
  applicationContextPath: /starfish/v1
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

logging:
  level: INFO
  loggers:
    datapunch.org: DEBUG
